/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asgteach.dialogs;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author gail
 */
public class CustomPersonPanel2 extends javax.swing.JPanel implements
        DocumentListener {
    
    public static String PROP_FIRST_NAME = "firstName";
    public static String PROP_LAST_NAME = "lastName";

    /**
     * Creates new form CustomPersonPanel
     */
    public CustomPersonPanel2() {
        initComponents();
        firstTextField.getDocument().addDocumentListener(this);
        lastTextField.getDocument().addDocumentListener(this);
    }
    
    public String getFirstName() {
        return firstTextField.getText();
    }
    
    public String getLastName() {
        return lastTextField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstTextField = new javax.swing.JTextField();
        lastTextField = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(CustomPersonPanel2.class, "CustomPersonPanel2.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(CustomPersonPanel2.class, "CustomPersonPanel2.jLabel2.text")); // NOI18N

        firstTextField.setText(org.openide.util.NbBundle.getMessage(CustomPersonPanel2.class, "CustomPersonPanel2.firstTextField.text")); // NOI18N

        lastTextField.setText(org.openide.util.NbBundle.getMessage(CustomPersonPanel2.class, "CustomPersonPanel2.lastTextField.text")); // NOI18N

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asgteach/dialogs/resources/personIcon100.png"))); // NOI18N
        imageLabel.setText(org.openide.util.NbBundle.getMessage(CustomPersonPanel2.class, "CustomPersonPanel2.imageLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastTextField)
                    .addComponent(firstTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(imageLabel)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lastTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(imageLabel)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lastTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent de) {
        if (firstTextField.getDocument() == de.getDocument()) {
            firePropertyChange(PROP_FIRST_NAME, 0, 1);
        } else if (lastTextField.getDocument() == de.getDocument()) {
            firePropertyChange(PROP_LAST_NAME, 0, 1);
        }
    }

    @Override
    public void removeUpdate(DocumentEvent de) {
        if (firstTextField.getDocument() == de.getDocument()) {
            firePropertyChange(PROP_FIRST_NAME, 0, 1);
        } else if (lastTextField.getDocument() == de.getDocument()) {
            firePropertyChange(PROP_LAST_NAME, 0, 1);
        }
    }

    @Override
    public void changedUpdate(DocumentEvent de) {
        if (firstTextField.getDocument() == de.getDocument()) {
            firePropertyChange(PROP_FIRST_NAME, 0, 1);
        } else if (lastTextField.getDocument() == de.getDocument()) {
            firePropertyChange(PROP_LAST_NAME, 0, 1);
        }
    }
}
