/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asgteach.usermodule;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//com.asgteach.usermodule//UserExplorer//EN",
autostore = false)
@TopComponent.Description(preferredID = "UserExplorerTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(
        roles = {"User"},
        mode = "explorer", 
        openAtStartup = true)
@TopComponent.OpenActionRegistration(displayName = "#CTL_UserExplorerAction",
preferredID = "UserExplorerTopComponent")
@Messages({
    "CTL_UserExplorerAction=UserExplorer",
    "CTL_UserExplorerTopComponent=UserExplorer Window",
    "HINT_UserExplorerTopComponent=This is a UserExplorer window"
})
public final class UserExplorerTopComponent extends TopComponent {

    public UserExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_UserExplorerTopComponent());
        setToolTipText(Bundle.HINT_UserExplorerTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
