/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asgteach.familytree.personviewer;

import com.asgteach.familytree.model.FamilyTreeManager;
import com.asgteach.familytree.model.Person;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.LifecycleManager;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.asgteach.familytree.personviewer//PersonViewer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "PersonViewerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "com.asgteach.familytree.personviewer.PersonViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_PersonViewerAction",
        preferredID = "PersonViewerTopComponent"
)
@Messages({
    "CTL_PersonViewerAction=PersonViewer",
    "CTL_PersonViewerTopComponent=PersonViewer Window",
    "HINT_PersonViewerTopComponent=This is a PersonViewer window"
})
public final class PersonViewerTopComponent extends TopComponent {
    
    private FamilyTreeManager ftm;
    private final DefaultMutableTreeNode top =  new DefaultMutableTreeNode("People");
    private final DefaultTreeModel treeModel = new DefaultTreeModel(top);
    private static final Logger logger = Logger.getLogger(PersonViewerTopComponent.class.getName());
    private final InstanceContent instanceContent = new InstanceContent();
    

    public PersonViewerTopComponent() {
        initComponents();
        setName(Bundle.CTL_PersonViewerTopComponent());
        setToolTipText(Bundle.HINT_PersonViewerTopComponent());
        associateLookup(new AbstractLookup(instanceContent));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personTree = new javax.swing.JTree(treeModel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personTree, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(personTree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree personTree;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        ftm = Lookup.getDefault().lookup(FamilyTreeManager.class); //obtengo un service provider
        if(ftm == null){
            logger.log(Level.SEVERE,"Cannot get family tree manager object");
            LifecycleManager.getDefault().exit();
        }
        //buildData();
        ftm.addPropertyChangeListener(familyTreeListener);
        personTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        createNodes();
        personTree.addTreeSelectionListener(treeSelectionListener);
    }

    @Override
    public void componentClosed() {
        personTree.removeTreeSelectionListener(treeSelectionListener);
        ftm.removePropertyChangeListener(familyTreeListener);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    
    //si el familytreemanager dispara un update... ejecuta este código (Actualizar el Arbol)
    private final PropertyChangeListener familyTreeListener = (PropertyChangeEvent evt) -> {
        //Busco el nodo y lo actualizo
        if(evt.getNewValue() != null && evt.getPropertyName().equals(FamilyTreeManager.PROP_PERSON_UPDATED)){
            Person person = (Person) evt.getNewValue();
            DefaultTreeModel model = (DefaultTreeModel) personTree.getModel();
            for(int i = 0; i<model.getChildCount(top);i++){
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) model.getChild(top, i);
                if(person.equals(node.getUserObject())){
                    node.setUserObject(person);
                    model.nodeChanged(node);
                    logger.log(Level.FINE,"Node updated: {0}", node);
                    break;
                }
            }
        }
    };
    
    
    //Se activa cuando selecciono un nodo
    private final TreeSelectionListener treeSelectionListener = (TreeSelectionEvent e) -> {
        //Obtengo el nodo seleccionado
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) personTree.getLastSelectedPathComponent();
        if(node == null){ //Si el nodo es null
            return;
        }
        if(node.isLeaf()){ //si el nodo es hoja
            Person person = (Person) node.getUserObject(); //creo un objeto user
            logger.log(Level.FINE,"{0} selected", person);
            //publico el nodo en el LookUp de la pantalla
            instanceContent.set(Collections.singleton(person),null);
        }
        else{ //no es hoja (El nodo Person), remuevo el previo Person del lookup
            logger.log(Level.INFO,"{0} selected",node.getUserObject());
            Person person = getLookup().lookup(Person.class);
            if(person != null){
                instanceContent.remove(person);
            }
        }
        
    };
    
    //Método que obtiene la Lista de personas del familyTreeManager y las agrega
    //al árbol en forma de nodos.
    private void createNodes(){
        ftm.getAllPeople().forEach((p)-> {
            top.add(new DefaultMutableTreeNode(p));
        });
        //Expando el arbol
        if(top.getChildCount() != 0){
            TreeNode[] nodes = treeModel.getPathToRoot(top.getLastChild());
            TreePath path = new TreePath(nodes);
            personTree.scrollPathToVisible(path);
        }
    }
}
