/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asgteach.newpizza;

import com.asgteach.customer.api.Customer;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.util.NbBundle;

public final class DeliveryInfoVisual extends JPanel {

    public static final String PROP_CUSTOMER_INFO = "customerInfo";
    private Customer customer;
    private boolean isReady = false;
    private DeliveryChange deliveryChange = new DeliveryChange();

    /**
     * Creates new form DeliveryInfoVisual
     */
    public DeliveryInfoVisual() {
        initComponents();
        addressTextField.getDocument().addDocumentListener(deliveryChange);
        creditCardTextField.getDocument().addDocumentListener(deliveryChange);
        phoneTextField.getDocument().addDocumentListener(deliveryChange);
    }

    private final class DeliveryChange implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent de) {
            fireChange(de);
        }

        @Override
        public void removeUpdate(DocumentEvent de) {
            fireChange(de);
        }

        @Override
        public void changedUpdate(DocumentEvent de) {
            fireChange(de);
        }

        private void fireChange(DocumentEvent de) {
            if (addressTextField.getDocument() == de.getDocument()
                    || creditCardTextField.getDocument() == de.getDocument()
                    || phoneTextField.getDocument() == de.getDocument()) {
                if (isReady) {
                    updateCustomer();
                    firePropertyChange(PROP_CUSTOMER_INFO, 0, 1);
                }
            }
        }
    }

    private void updateCustomer() {
        customer.setAddress(addressTextField.getText());
        customer.setPhone(phoneTextField.getText());
        customer.setCreditCard(creditCardTextField.getText());
    }

    public void setCustomer(Customer customer) {
        isReady = false;
        this.customer = customer;
        customerNameLabel.setText(this.customer.getName());
        phoneTextField.setText(this.customer.getPhone());
        addressTextField.setText(this.customer.getAddress());
        creditCardTextField.setText(this.customer.getCreditCard());
        isReady = true;
    }

    public Customer getCustomer() {
        return this.customer;
    }

    @NbBundle.Messages({"CTL_Panel4Name=Delivery Information"})
    @Override
    public String getName() {
        return Bundle.CTL_Panel4Name();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        creditCardTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DeliveryInfoVisual.class, "DeliveryInfoVisual.jLabel2.text")); // NOI18N

        addressTextField.setText(org.openide.util.NbBundle.getMessage(DeliveryInfoVisual.class, "DeliveryInfoVisual.addressTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(DeliveryInfoVisual.class, "DeliveryInfoVisual.jLabel3.text")); // NOI18N

        phoneTextField.setText(org.openide.util.NbBundle.getMessage(DeliveryInfoVisual.class, "DeliveryInfoVisual.phoneTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DeliveryInfoVisual.class, "DeliveryInfoVisual.jLabel1.text")); // NOI18N

        creditCardTextField.setText(org.openide.util.NbBundle.getMessage(DeliveryInfoVisual.class, "DeliveryInfoVisual.creditCardTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(DeliveryInfoVisual.class, "DeliveryInfoVisual.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(customerNameLabel, org.openide.util.NbBundle.getMessage(DeliveryInfoVisual.class, "DeliveryInfoVisual.customerNameLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creditCardTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(addressTextField)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(creditCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField creditCardTextField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField phoneTextField;
    // End of variables declaration//GEN-END:variables
}
