/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asgteach.familytree.utilities;

/**
 *
 * @author gail
 */
public class HappyMammothPanel extends javax.swing.JPanel {

    /**
     * Creates new form HappyMammothPanel
     */
    public HappyMammothPanel() {
        initComponents();
    }
    
    public void setText(String text) {
        panelLabel.setText(text);
        panelLabel.getParent().revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        panelLabel = new javax.swing.JLabel();

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asgteach/familytree/utilities/happy_mammoth75.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(imageLabel, org.openide.util.NbBundle.getMessage(HappyMammothPanel.class, "HappyMammothPanel.imageLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(panelLabel, org.openide.util.NbBundle.getMessage(HappyMammothPanel.class, "HappyMammothPanel.panelLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(imageLabel)
                .addGap(18, 18, 18)
                .addComponent(panelLabel)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imageLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(panelLabel)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel panelLabel;
    // End of variables declaration//GEN-END:variables
}
