/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asgteach.sequence;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.netbeans.validation.api.Problem;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.openide.util.NbBundle;

public final class NumberVisualPanel1 extends JPanel {

    // Create property names for each piece of data that
    // we want to collect
    public static final String PROP_FIRST_NUMBER = "firstNumber";
    public static final Integer MAX_SEQUENCE_NUMBER = 10000; // arbitrary
    private ValidationGroup group = null;
    private boolean isValid = false;

    /**
     * Creates new form NumberVisualPanel1
     */
    @SuppressWarnings("unchecked")
    public NumberVisualPanel1() {
        initComponents();
        firstNumber.setName(Bundle.CTL_Panel1FieldName());
        group = validationPanel1.getValidationGroup();

        group.add(firstNumber,
                Validators.REQUIRE_NON_EMPTY_STRING,
                Validators.NO_WHITESPACE,
                Validators.REQUIRE_VALID_INTEGER,
                Validators.REQUIRE_NON_NEGATIVE_NUMBER,
                Validators.numberRange(0, MAX_SEQUENCE_NUMBER-2));

        firstNumber.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                checkValidation();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkValidation();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkValidation();
            }

            private void checkValidation() {
                Problem validateAll = group.validateAll();
                isValid = !validateAll.isFatal();
                firePropertyChange(PROP_FIRST_NUMBER, 0, 1);
            }
        });
    }

    @NbBundle.Messages({"CTL_Panel1Name=Provide Sequence Initial Value"})
    @Override
    public String getName() {
        return Bundle.CTL_Panel1Name();
    }

    public String getFirstNumber() {
        return firstNumber.getText();
    }

    @Override
    public boolean isValid() {
        return isValid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firstNumber = new javax.swing.JTextField();
        validationPanel1 = new org.netbeans.validation.api.ui.ValidationPanel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NumberVisualPanel1.class, "NumberVisualPanel1.jLabel1.text")); // NOI18N

        firstNumber.setText(org.openide.util.NbBundle.getMessage(NumberVisualPanel1.class, "NumberVisualPanel1.firstNumber.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(firstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel1)))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addComponent(validationPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(firstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField firstNumber;
    private javax.swing.JLabel jLabel1;
    private org.netbeans.validation.api.ui.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
