/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asgteach.sequence;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.netbeans.validation.api.Problem;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.openide.util.NbBundle;

public final class NumberVisualPanel2 extends JPanel {

    public static final String PROP_SECOND_NUMBER = "secondNumber";
    private boolean isValid = false;
    private final CustomRangeValidator customrange = new CustomRangeValidator();
    private ValidationGroup group = null;

    /**
     * Creates new form NumberVisualPanel2
     */
    @SuppressWarnings("unchecked")
    public NumberVisualPanel2() {
        initComponents();
        secondNumber.setName(Bundle.CTL_Panel1FieldName());

        // setup validation
        group = validationPanel1.getValidationGroup();
        customrange.setMaxVal(NumberVisualPanel1.MAX_SEQUENCE_NUMBER - 1);
        customrange.setMinVal(0);

        group.add(secondNumber,
                Validators.REQUIRE_NON_EMPTY_STRING,
                Validators.NO_WHITESPACE,
                Validators.REQUIRE_VALID_INTEGER,
                Validators.REQUIRE_NON_NEGATIVE_NUMBER,
                customrange);
        secondNumber.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent de) {
                checkValidation();
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                checkValidation();
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
                checkValidation();
            }

            private void checkValidation() {
                updateValidation();
                firePropertyChange(PROP_SECOND_NUMBER, 0, 1);
            }
        });
    }

    @NbBundle.Messages({"CTL_Panel2Name=Provide Sequence Second Value"})
    @Override
    public String getName() {
        return Bundle.CTL_Panel2Name();
    }

    public String getSecondNumber() {
        return secondNumber.getText();
    }

    public void setCurrentSequence(String text) {
        currentSequence.setText(text);
    }

    public void setMinRange(Integer minNumber) {
        customrange.setMinVal(minNumber);
    }

    public void updateValidation() {
        Problem validateAll = group.validateAll();
        isValid = !validateAll.isFatal();
    }

    @Override
    public boolean isValid() {
        return isValid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        secondNumber = new javax.swing.JTextField();
        currentSequence = new javax.swing.JLabel();
        validationPanel1 = new org.netbeans.validation.api.ui.ValidationPanel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NumberVisualPanel2.class, "NumberVisualPanel2.jLabel1.text")); // NOI18N

        secondNumber.setText(org.openide.util.NbBundle.getMessage(NumberVisualPanel2.class, "NumberVisualPanel2.secondNumber.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(currentSequence, org.openide.util.NbBundle.getMessage(NumberVisualPanel2.class, "NumberVisualPanel2.currentSequence.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(secondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(currentSequence, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(validationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(secondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(currentSequence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(validationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentSequence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField secondNumber;
    private org.netbeans.validation.api.ui.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
