/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.asgteach.newpizza;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.openide.util.NbBundle;

public final class BuildPizzaVisual extends JPanel {

    private PizzaChange pizzaChange = new PizzaChange();
    public static final String PROP_IS_PICKUP = "isPickup";

    public PizzaOrder getPizzaOrder() {
        return pizzaOrder;
    }

    private PizzaOrder.PizzaSize getPizzaSize() {
        if (smallRadioButton.isSelected()) {
            return PizzaOrder.PizzaSize.SMALL;
        } else if (mediumRadioButton.isSelected()) {
            return PizzaOrder.PizzaSize.MEDIUM;
        } else {
            return PizzaOrder.PizzaSize.LARGE;
        }
    }

    private boolean isPickup() {
        return pickupRadioButton.isSelected();
    }

    private Set<String> getToppings() {
        Set<String> toppings = new HashSet<>();
        if (pepperoniCheckBox.isSelected()) {
            toppings.add(PizzaOrder.pepperoni);
        }
        if (onionsCheckBox.isSelected()) {
            toppings.add(PizzaOrder.onions);
        }
        if (sausageCheckBox.isSelected()) {
            toppings.add(PizzaOrder.sausage);
        }
        return toppings;
    }

    private void updatePizza() {
        pizzaOrder.setPizzaSize(this.getPizzaSize());
        pizzaOrder.setToppings(this.getToppings());
        pizzaOrder.setPickup(this.isPickup());
    }

    /**
     * Creates new form BuildPizzaVisual
     */
    public BuildPizzaVisual() {
        initComponents();
        deliveryRadioButton.setSelected(true);
        smallRadioButton.setSelected(true);
        this.updatePizza();
        totalLabel.setText("$ " + pizzaOrder.getTotal());
        smallRadioButton.addChangeListener(pizzaChange);
        mediumRadioButton.addChangeListener(pizzaChange);
        largeRadioButton.addChangeListener(pizzaChange);

        pepperoniCheckBox.addChangeListener(pizzaChange);
        onionsCheckBox.addChangeListener(pizzaChange);
        sausageCheckBox.addChangeListener(pizzaChange);

        pickupRadioButton.addChangeListener(pizzaChange);
    }

    private final class PizzaChange implements ChangeListener {

        @Override
        public void stateChanged(ChangeEvent ce) {
            updatePizza();
            totalLabel.setText("$ " + pizzaOrder.getTotal());
            firePropertyChange(PROP_IS_PICKUP, 0, 1);
        }
    }

    @NbBundle.Messages({"CTL_Panel3Name=Size and Toppings"})
    @Override
    public String getName() {
        return Bundle.CTL_Panel3Name();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeButtonGroup = new javax.swing.ButtonGroup();
        pickupDeliveryButtonGroup = new javax.swing.ButtonGroup();
        pizzaOrder = new com.asgteach.newpizza.PizzaOrder();
        jLabel1 = new javax.swing.JLabel();
        smallRadioButton = new javax.swing.JRadioButton();
        mediumRadioButton = new javax.swing.JRadioButton();
        largeRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        pepperoniCheckBox = new javax.swing.JCheckBox();
        sausageCheckBox = new javax.swing.JCheckBox();
        onionsCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        pickupRadioButton = new javax.swing.JRadioButton();
        deliveryRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.jLabel1.text")); // NOI18N

        sizeButtonGroup.add(smallRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(smallRadioButton, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.smallRadioButton.text")); // NOI18N

        sizeButtonGroup.add(mediumRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(mediumRadioButton, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.mediumRadioButton.text")); // NOI18N

        sizeButtonGroup.add(largeRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(largeRadioButton, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.largeRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(pepperoniCheckBox, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.pepperoniCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sausageCheckBox, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.sausageCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(onionsCheckBox, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.onionsCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.jLabel3.text")); // NOI18N

        pickupDeliveryButtonGroup.add(pickupRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(pickupRadioButton, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.pickupRadioButton.text")); // NOI18N

        pickupDeliveryButtonGroup.add(deliveryRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(deliveryRadioButton, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.deliveryRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(BuildPizzaVisual.class, "BuildPizzaVisual.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(smallRadioButton)
                            .addComponent(mediumRadioButton)
                            .addComponent(largeRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(sausageCheckBox)
                            .addComponent(onionsCheckBox)
                            .addComponent(pepperoniCheckBox))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pickupRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deliveryRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smallRadioButton)
                    .addComponent(pepperoniCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediumRadioButton)
                    .addComponent(sausageCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(largeRadioButton)
                    .addComponent(onionsCheckBox))
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pickupRadioButton)
                    .addComponent(deliveryRadioButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton deliveryRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton largeRadioButton;
    private javax.swing.JRadioButton mediumRadioButton;
    private javax.swing.JCheckBox onionsCheckBox;
    private javax.swing.JCheckBox pepperoniCheckBox;
    private javax.swing.ButtonGroup pickupDeliveryButtonGroup;
    private javax.swing.JRadioButton pickupRadioButton;
    private com.asgteach.newpizza.PizzaOrder pizzaOrder;
    private javax.swing.JCheckBox sausageCheckBox;
    private javax.swing.ButtonGroup sizeButtonGroup;
    private javax.swing.JRadioButton smallRadioButton;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
